# 北港冷知識
1. Google map上的營業中不可信
2. 有些店說8點關,其實6點就賣完
3. 李記誠可貴,新港價更高(鴨肉羹)
4. 農曆3/19~3/23,去藝閣撿東西
5. 馬祖遶境,免費食物吃到飽
6. 綠豆湯阿北,不定時送免費food(其實是賣當歸鴨的)
7. 301(公車)帶你體驗雲霄飛車般的刺激
8. 9015直達台中
9. 107一間無人管束,24小時營業的“自習室”
10. 宵夜好夥伴,斗南炸饅頭
11. 熱水表訂1點沒,其實2點、3點都還是熱的
12. 加入家樂福的line,送貨到學校
13. 滿200,大部分飲料店可送貨上門
14. 去馬祖醫院看病,批價時,給學生證有折扣或不用錢
15. 每逢3、6、9,北港大橋有牛墟(早上市集)可逛

# 期末複習